<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Nodes\**" />
    <EmbeddedResource Remove="Nodes\**" />
    <None Remove="Nodes\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DvElements\DvElementAdditionRange.cs" />
    <Compile Remove="DvElements\DvElementBloom.cs" />
    <Compile Remove="DvElements\DvElementCameraShake.cs" />
    <Compile Remove="DvElements\DvElementChangeTimeScale.cs" />
    <Compile Remove="DvElements\DvElementCompositeAnimation.cs" />
    <Compile Remove="DvElements\DvElementCrossFade.cs" />
    <Compile Remove="DvElements\DvElementGeneralTrigger.cs" />
    <Compile Remove="DvElements\DvElementLipAnimation.cs" />
    <Compile Remove="DvElements\DvElementLookAtIK.cs" />
    <Compile Remove="DvElements\DvElementModelFade.cs" />
    <Compile Remove="DvElements\DvElementOverrideASM.cs" />
    <Compile Remove="DvElements\DvElementQTE.cs" />
    <Compile Remove="DvElements\DvElementRifleBeastLighting.cs" />
    <Compile Remove="DvElements\DvElementShadowMapParam.cs" />
    <Compile Remove="DvElements\DvElementSonicCamera.cs" />
    <Compile Remove="DvElements\DvElementSpotlight.cs" />
    <Compile Remove="DvElements\DvElementTheEndCableObject.cs" />
    <Compile Remove="DvElements\DvElementVertexAnimation.cs" />
    <Compile Remove="Helper.cs" />
    <Compile Remove="Reader.cs" />
    <Compile Remove="Resource.cs" />
    <Compile Remove="Writer.cs" />
  </ItemGroup>
	
  <ItemGroup>
	<ProjectReference Include="..\Amicitia.IO\src\Amicitia.IO\Amicitia.IO.csproj" />
  </ItemGroup>

</Project>
