<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Nodes\**" />
    <EmbeddedResource Remove="Nodes\**" />
    <None Remove="Nodes\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DvElements\DvElementAdditionRange.cs" />
    <Compile Remove="DvElements\DvElementAtmosphereHeightFogParam.cs" />
    <Compile Remove="DvElements\DvElementAura.cs" />
    <Compile Remove="DvElements\DvElementAuraRoad.cs" />
    <Compile Remove="DvElements\DvElementBloom.cs" />
    <Compile Remove="DvElements\DvElementBossName.cs" />
    <Compile Remove="DvElements\DvElementCameraBlur.cs" />
    <Compile Remove="DvElements\DvElementCameraExposure.cs" />
    <Compile Remove="DvElements\DvElementCameraOffset.cs" />
    <Compile Remove="DvElements\DvElementCameraShake.cs" />
    <Compile Remove="DvElements\DvElementCameraShakeLoop.cs" />
    <Compile Remove="DvElements\DvElementChangeTimeScale.cs" />
    <Compile Remove="DvElements\DvElementChromaticAberrationFilter.cs" />
    <Compile Remove="DvElements\DvElementColorContrast.cs" />
    <Compile Remove="DvElements\DvElementCompositeAnimation.cs" />
    <Compile Remove="DvElements\DvElementCrossFade.cs" />
    <Compile Remove="DvElements\DvElementCulling.cs" />
    <Compile Remove="DvElements\DvElementCyberSpaceNoise.cs" />
    <Compile Remove="DvElements\DvElementDither.cs" />
    <Compile Remove="DvElements\DvElementDOF.cs" />
    <Compile Remove="DvElements\DvElementDrawOff.cs" />
    <Compile Remove="DvElements\DvElementEffect.cs" />
    <Compile Remove="DvElements\DvElementGeneralTrigger.cs" />
    <Compile Remove="DvElements\DvElementLipAnimation.cs" />
    <Compile Remove="DvElements\DvElementLookAtIK.cs" />
    <Compile Remove="DvElements\DvElementMaterialAnimation.cs" />
    <Compile Remove="DvElements\DvElementModelClipping.cs" />
    <Compile Remove="DvElements\DvElementModelFade.cs" />
    <Compile Remove="DvElements\DvElementNearFarSetting.cs" />
    <Compile Remove="DvElements\DvElementOverrideASM.cs" />
    <Compile Remove="DvElements\DvElementPathAdjustment.cs" />
    <Compile Remove="DvElements\DvElementPathInterpolation.cs" />
    <Compile Remove="DvElements\DvElementQTE.cs" />
    <Compile Remove="DvElements\DvElementRifleBeastLighting.cs" />
    <Compile Remove="DvElements\DvElementShadowMapParam.cs" />
    <Compile Remove="DvElements\DvElementShadowResolution.cs" />
    <Compile Remove="DvElements\DvElementSonicCamera.cs" />
    <Compile Remove="DvElements\DvElementSound.cs" />
    <Compile Remove="DvElements\DvElementSpotlight.cs" />
    <Compile Remove="DvElements\DvElementSun.cs" />
    <Compile Remove="DvElements\DvElementTheEndCableObject.cs" />
    <Compile Remove="DvElements\DvElementTime.cs" />
    <Compile Remove="DvElements\DvElementUVAnimation.cs" />
    <Compile Remove="DvElements\DvElementVariablePointLight.cs" />
    <Compile Remove="DvElements\DvElementVertexAnimation.cs" />
    <Compile Remove="DvElements\DvElementVignette.cs" />
    <Compile Remove="DvElements\DvElementVisibilityAnimation.cs" />
    <Compile Remove="DvElements\DvElementWeather.cs" />
    <Compile Remove="DvNodes\DvNodeCharacter.cs" />
    <Compile Remove="DvNodes\DvNodeCharacterMotion.cs" />
    <Compile Remove="DvNodes\DvNodeModelCustom.cs" />
    <Compile Remove="DvNodes\DvNodeModelNode.cs" />
    <Compile Remove="DvNodes\DvNodeMotionModel.cs" />
    <Compile Remove="Helper.cs" />
    <Compile Remove="Reader.cs" />
    <Compile Remove="Resource.cs" />
    <Compile Remove="Writer.cs" />
  </ItemGroup>
	
  <ItemGroup>
	<ProjectReference Include="..\Amicitia.IO\src\Amicitia.IO\Amicitia.IO.csproj" />
  </ItemGroup>

</Project>
